package com.github.macgarcia.access.control.desktop.view.configuracoes;

import com.github.macgarcia.access.control.desktop.component.ManipulacaoDeArquivoTxt;
import com.github.macgarcia.access.control.desktop.configuration.FactoryLog;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author macgarcia
 */
public class TelaDeLogs extends javax.swing.JInternalFrame {
    
    private static final Logger LOGGER = FactoryLog.getLog();
    
    private final String DIR_LOG_FILE = "log";
    private final String ARQ_LOG_FILE = "arq_log.log";
    private final String PATH_LOG_FILE = DIR_LOG_FILE + File.separator + ARQ_LOG_FILE;
    
    private final int MAX_LINHAS = 1_000_000;
    private List<String> linhasDoLog;
    private DefaultListModel<String> modeloLista;

    /**
     * Creates new form TelaDeLogs
     */
    public TelaDeLogs() {
        initComponents();
        modeloLista = new DefaultListModel();
        configurarJanela();
        lerDados();
        populandoJList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeLogs = new javax.swing.JList<>();

        setClosable(true);

        jLabel1.setText("Logs do sistema");

        listaDeLogs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDeLogs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(698, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaDeLogs;
    // End of variables declaration//GEN-END:variables

    private void configurarJanela() {
        setTitle("Logs do sistema");
        setResizable(false);
    }
    
    private void lerDados() {
        try {
            carregandoArquivoDeLog();
        } catch (IOException ex) {
            LOGGER.severe(String.format("Erro ao ler o arquivo de logs.: [%s]", ex.getMessage()));
        }
    }
    
    private void carregandoArquivoDeLog() throws IOException {
        linhasDoLog = ManipulacaoDeArquivoTxt.lerAqruivo(PATH_LOG_FILE, MAX_LINHAS);
    }
    
    private void populandoJList() {
        for (String linha : this.linhasDoLog) {
            modeloLista.addElement(linha);
        }
        this.listaDeLogs.setModel(modeloLista);
    }

}
