package com.github.macgarcia.access.control.desktop.view.financeiro;

import com.github.macgarcia.access.control.desktop.component.ModeloTabelaDivida;
import com.github.macgarcia.access.control.desktop.configuration.Configuracao;
import com.github.macgarcia.access.control.desktop.configuration.FactoryMensagem;
import com.github.macgarcia.access.control.desktop.enuns.CategoriaDivida;
import com.github.macgarcia.access.control.desktop.enuns.Mes;
import com.github.macgarcia.access.control.desktop.model.financeiro.Divida;
import java.time.LocalDate;
import java.util.Objects;

/**
 *
 * @author macgarcia
 */
public class TelaCadastroDivida extends javax.swing.JInternalFrame {
    
    private Divida dividaSelecionada;
    private Divida novaDivida;
    private ModeloTabelaDivida model;

    /**
     * Creates new form TelaCadastroDivida
     */
    public TelaCadastroDivida() {
        initComponents();
        configurarJanela();
        startCombos();
        acoesComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDataDivida = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Descrição");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mes referência");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Categoria");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSalvar.setText("Salvar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao)
                    .addComponent(txtValor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addComponent(jDataDivida, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(comboMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDataDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboMes;
    private com.toedter.calendar.JDateChooser jDataDivida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void configurarJanela() {
        this.setTitle("Cadastro de divida");
        this.setResizable(false);
        jDataDivida.setDateFormatString("dd/MM/yyyy");
    }

    private void startCombos() {
        Configuracao.startComboMes(comboMes);
        Configuracao.startComboCategoria(comboCategoria);
    }

    public void mostrarDados(Divida dividaSelecionada) {
        this.dividaSelecionada = dividaSelecionada;
        montarTelaEdicaoComDados();
    }

    private void montarTelaEdicaoComDados() {
        txtDescricao.setText(dividaSelecionada.getDescricao());
        txtValor.setText(dividaSelecionada.getValor().toString());
        jDataDivida.setDate(Configuracao.localDateToDate(dividaSelecionada.getDataDivida()));
        comboMes.setSelectedIndex(dividaSelecionada.getMes().ordinal());
        comboCategoria.setSelectedIndex(dividaSelecionada.getCategoria().ordinal() + 1);
    }

    private void acoesComponentes() {
        btnSalvar.addActionListener(ev -> {
            if (validarDadosDoFormulario()) {
                capturarInformacoesDaTela();
                model.salvarDivida(novaDivida);
                FactoryMensagem.mensagemOk("Divida salva com sucesso.");
                dispose();
            }
        });
    }

    private boolean validarDadosDoFormulario() {
        if (txtDescricao.getText().isBlank()) {
            FactoryMensagem.mensagemAlerta("Descrição não pode ser nulo.");
            return false;
        }
        if (!Configuracao.validarSeHaApenasNumeros(txtValor.getText())) {
            FactoryMensagem.mensagemAlerta("Digite apenas numeros no campo valor.");
            return false;
        }
        LocalDate date = Configuracao.dateToLocalDate(jDataDivida.getDate());
        if (Objects.isNull(date)) {
            FactoryMensagem.mensagemAlerta("Data não pode ser nulo.");
            return false;
        }
        return true;
    }

    private void capturarInformacoesDaTela() {
        String descricao = txtDescricao.getText();
        String valor = txtValor.getText();
        LocalDate date = Configuracao.dateToLocalDate(jDataDivida.getDate());
        Mes mes = Mes.getMesComDigito(comboMes.getSelectedIndex());
        CategoriaDivida categoria = CategoriaDivida.get(comboCategoria.getSelectedIndex());
        novaDivida = new Divida(descricao,
                "".equals(valor) ? null : Double.valueOf(valor),
                date,
                mes,
                categoria);
    }

    public void setModel(ModeloTabelaDivida model) {
        this.model = model;
    }

}
