package com.github.macgarcia.access.control.desktop.view.financeiro;

import com.github.macgarcia.access.control.desktop.component.ModeloTabelaDivida;
import com.github.macgarcia.access.control.desktop.configuration.Configuracao;
import com.github.macgarcia.access.control.desktop.configuration.FactoryMensagem;
import com.github.macgarcia.access.control.desktop.configuration.FactoryTela;
import com.github.macgarcia.access.control.desktop.model.financeiro.Divida;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import javax.swing.JDesktopPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author macgarcia
 */
public class TelaContaDoMes extends javax.swing.JInternalFrame {

    private ModeloTabelaDivida model = new ModeloTabelaDivida();
    private JDesktopPane desktop;
    private Divida dividaSelecionada;
    
    /* Quando houver uma ação de inserção e atualização de dados */
    private boolean precisaRecarregarATabela = false;

    /**
     * Creates new form ContaDoMes
     */
    public TelaContaDoMes() {
        initComponents();
        configurarJanela();
        startComboMes();
        startComboCategoria();
        construirTabelaDividas();
        acoesDosBotoes();
        eventosDaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDividas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtValorSaldoMensal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValorTotalDeDividas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtValorResultante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnNovaDivida = new javax.swing.JButton();
        btnAtualizarDivida = new javax.swing.JButton();
        btnExcluirDivida = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mes atual");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Categoria");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabelaDividas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaDividas);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Lista de dividas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Valor saldo mensal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Valor total de dividas");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Valor resultante");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Menus");

        btnNovaDivida.setBackground(new java.awt.Color(51, 153, 0));
        btnNovaDivida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovaDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaDivida.setText("Nova divida");

        btnAtualizarDivida.setBackground(new java.awt.Color(0, 51, 255));
        btnAtualizarDivida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarDivida.setText("Atualizar divida");

        btnExcluirDivida.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluirDivida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirDivida.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirDivida.setText("Excluir divida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtValorResultante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(txtValorTotalDeDividas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtValorSaldoMensal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel2)
                                .addGap(188, 188, 188)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btnNovaDivida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizarDivida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirDivida)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaDivida)
                    .addComponent(btnAtualizarDivida)
                    .addComponent(btnExcluirDivida))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorSaldoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotalDeDividas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorResultante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarDivida;
    private javax.swing.JButton btnExcluirDivida;
    private javax.swing.JButton btnNovaDivida;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaDividas;
    private javax.swing.JTextField txtValorResultante;
    private javax.swing.JTextField txtValorSaldoMensal;
    private javax.swing.JTextField txtValorTotalDeDividas;
    // End of variables declaration//GEN-END:variables

    private void configurarJanela() {
        this.setTitle("Contas do mês");
        this.setResizable(false);
    }

    private void startComboMes() {
        Configuracao.startComboMes(comboMes);
    }

    private void startComboCategoria() {
        Configuracao.startComboCategoria(comboCategoria);
    }

    private void construirTabelaDividas() {
        this.tabelaDividas.setModel(model);
        this.tabelaDividas.getTableHeader().setReorderingAllowed(false);
    }

    private void reconstruirTabelaDividas() {
        model = new ModeloTabelaDivida();
        construirTabelaDividas();
    }

    private void acoesDosBotoes() {
        this.btnNovaDivida.addActionListener(ev -> abrirTelaDeCadastroDivida());
        this.btnAtualizarDivida.addActionListener(ev -> abrirTelaDeEditarDivida());
        this.btnExcluirDivida.addActionListener(ev -> {
        });
    }

    private void eventosDaTela() {
        tabelaDividas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dividaSelecionada = model.getDivida(tabelaDividas.getSelectedRow());
                if (e.getClickCount() == 2) {
                    abrirTelaDeEditarDivida();
                }
            }
        });

        this.addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                if (precisaRecarregarATabela) {
                    reconstruirTabelaDividas();
                    precisaRecarregarATabela = false;
                }
            }

        });
    }

    /* Abre a tela de cadastro em formato primario */
    private void abrirTelaDeCadastroDivida() {
        precisaRecarregarATabela = true;
        if (Configuracao.verificarJanelaAberta(this.desktop, TelaCadastroDivida.class)) {
            FactoryMensagem.mensagemAlerta("Tela de cadastro esta aberta em sua area de trabalho.");
        } else {
            TelaCadastroDivida tela = FactoryTela.criarTela(TelaCadastroDivida.class, desktop);
            tela.setModel(model);
        }
    }

    /* Abre a tela de cadastro em formato secundário - edição */
    private void abrirTelaDeEditarDivida() {
        precisaRecarregarATabela = true;
        if (Configuracao.verificarJanelaAberta(this.desktop, TelaCadastroDivida.class)) {
            FactoryMensagem.mensagemAlerta("Tela de cadastro esta aberta em sua area de trabalho.");
        } else {
            if (Objects.isNull(dividaSelecionada)) {
                FactoryMensagem.mensagemAlerta("Selecione um registro.");
            } else {
                TelaCadastroDivida tela = FactoryTela.criarTela(TelaCadastroDivida.class, desktop);
                tela.mostrarDados(dividaSelecionada);
                tela.setModel(model);
            }
        }
    }

    public void setDesktop(JDesktopPane desktopPanel) {
        this.desktop = desktopPanel;
    }

}
