package com.github.macgarcia.access.control.desktop.view.financeiro;

import com.github.macgarcia.access.control.desktop.component.ModeloTabelaCalculoMensal;
import com.github.macgarcia.access.control.desktop.configuration.Configuracao;
import com.github.macgarcia.access.control.desktop.configuration.FactoryMensagem;
import com.github.macgarcia.access.control.desktop.enuns.Mes;
import com.github.macgarcia.access.control.desktop.model.financeiro.CalculoMensal;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author macgarcia
 */
public class TelaFechamentoMensal extends javax.swing.JInternalFrame {

    private ModeloTabelaCalculoMensal model = new ModeloTabelaCalculoMensal();
    private CalculoMensal calculoMensalSelecionado;

    /**
     * Creates new form TelaFechamentoMensal
     */
    public TelaFechamentoMensal() {
        initComponents();
        configurarJanela();
        startComboMes();
        construirTabelaDeCalculos();
        acaoDosBotoes();
        eventosDaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProcessar = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtValorMensalRecebido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCalculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Menus");

        btnProcessar.setBackground(new java.awt.Color(0, 153, 0));
        btnProcessar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProcessar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessar.setText("Processar fechamento mensal");

        btnDesfazer.setBackground(new java.awt.Color(153, 153, 153));
        btnDesfazer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDesfazer.setText("Desfazer fechamento mensal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Valor mensal recebido");

        tabelaCalculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaCalculos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Dados de fechamento mensais");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(606, 606, 606))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comboMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnProcessar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDesfazer)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorMensalRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcessar)
                    .addComponent(btnDesfazer)
                    .addComponent(txtValorMensalRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCalculos;
    private javax.swing.JTextField txtValorMensalRecebido;
    // End of variables declaration//GEN-END:variables

    private void configurarJanela() {
        setTitle("Fechamento mensal");
        setResizable(false);
    }

    private void startComboMes() {
        Configuracao.startComboMes(comboMes);
    }

    private void construirTabelaDeCalculos() {
        tabelaCalculos.setModel(model);
        tabelaCalculos.getTableHeader().setReorderingAllowed(false);
    }
    
    private void reconstruirTabelaDeCalculos() {
        model = new ModeloTabelaCalculoMensal();
        construirTabelaDeCalculos();
    }

    private void eventosDaTela() {
        tabelaCalculos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                calculoMensalSelecionado = model.getCalculoMensal(tabelaCalculos.getSelectedRow());
            }
        });
    }

    private void acaoDosBotoes() {
        btnProcessar.addActionListener(ev -> {
            if (txtValorMensalRecebido.getText().isBlank()) {
                FactoryMensagem.mensagemAlerta("Informe o valor mensal.");
            } else {
                if (Configuracao.validarSeHaApenasNumeros(txtValorMensalRecebido.getText())) {
                    Mes mesSelecionado = Mes.getMesComDigito(comboMes.getSelectedIndex());
                    Double valor = Double.valueOf(txtValorMensalRecebido.getText());
                    model.processarFechamentoMensal(mesSelecionado, valor);
                    reconstruirTabelaDeCalculos();
                } else {
                    FactoryMensagem.mensagemAlerta("Informe apenas numeros no campo valor mensal recebido.");
                }
            }
        });

        btnDesfazer.addActionListener(ev -> {
            if (!Objects.isNull(calculoMensalSelecionado)) {
                int mensagemConfirmacao = FactoryMensagem.mensagemConfirmacao();
                if (mensagemConfirmacao == JOptionPane.YES_OPTION) {
                    model.desfazerFechamentoMensal(calculoMensalSelecionado.getId());
                    reconstruirTabelaDeCalculos();
                }
            } else {
                FactoryMensagem.mensagemAlerta("Selecione um registro da desfazer...");
            }
        });
    }

}
