package com.github.macgarcia.access.control.desktop;

import com.github.macgarcia.access.control.desktop.configuration.Configuracao;
import com.github.macgarcia.access.control.desktop.configuration.FactoryMensagem;
import com.github.macgarcia.access.control.desktop.repository.DAOGenerico;
import com.github.macgarcia.access.control.desktop.view.TelaCadastroNota;
import com.github.macgarcia.access.control.desktop.view.TelaDeHistoricoNota;
import com.github.macgarcia.access.control.desktop.view.TelaTodasAnotacoes;
import javax.persistence.EntityManager;

/**
 *
 * @author macgarcia
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private final String MENSAGEM_DE_TELA_ABERTA = "A tela já esta aberta em sua area de trabalho.";

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setExtendedState(TelaInicial.MAXIMIZED_BOTH);
        configurarJanela();
        acoesDoMenuAnotacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuAnotacoes = new javax.swing.JMenu();
        btnItemMenuNovaNota = new javax.swing.JMenuItem();
        btnItemMenuTodasNotas = new javax.swing.JMenuItem();
        btnItemHistoricoDeNotas = new javax.swing.JMenuItem();
        btnItemMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        btnMenuAnotacoes.setText("Anotações");

        btnItemMenuNovaNota.setText("Cadastrar nova nota");
        btnMenuAnotacoes.add(btnItemMenuNovaNota);

        btnItemMenuTodasNotas.setText("Todas as notas");
        btnMenuAnotacoes.add(btnItemMenuTodasNotas);

        btnItemHistoricoDeNotas.setText("Histórico de atualizações das notas");
        btnMenuAnotacoes.add(btnItemHistoricoDeNotas);

        btnItemMenuSair.setText("Sair");
        btnMenuAnotacoes.add(btnItemMenuSair);

        jMenuBar1.add(btnMenuAnotacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnItemHistoricoDeNotas;
    private javax.swing.JMenuItem btnItemMenuNovaNota;
    private javax.swing.JMenuItem btnItemMenuSair;
    private javax.swing.JMenuItem btnItemMenuTodasNotas;
    private javax.swing.JMenu btnMenuAnotacoes;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void configurarJanela() {
        setTitle("Controle de acessos pessoais");
        setResizable(false);
    }

    private void acoesDoMenuAnotacoes() {

        this.btnItemMenuNovaNota.addActionListener(ev -> {
            if (Configuracao.verificarJanelaAberta(this.desktopPanel, TelaCadastroNota.class)) {
                FactoryMensagem.mensagemAlerta(MENSAGEM_DE_TELA_ABERTA);
            } else {
                TelaCadastroNota tela = new TelaCadastroNota();
                tela.setAtualizacaoDeNota(false);
                this.desktopPanel.add(tela);
                Configuracao.setPosicaoInternalFrame(desktopPanel, tela);
                tela.setVisible(true);
            }
        });

        this.btnItemMenuTodasNotas.addActionListener(ev -> {
            if (Configuracao.verificarJanelaAberta(desktopPanel, TelaTodasAnotacoes.class)) {
                FactoryMensagem.mensagemAlerta(MENSAGEM_DE_TELA_ABERTA);
            } else {
                TelaTodasAnotacoes tela = new TelaTodasAnotacoes(desktopPanel);
                this.desktopPanel.add(tela);
                Configuracao.setPosicaoInternalFrame(desktopPanel, tela);
                tela.setVisible(true);
            }
        });
        
        this.btnItemHistoricoDeNotas.addActionListener(ev -> {
            if (Configuracao.verificarJanelaAberta(desktopPanel, TelaDeHistoricoNota.class)) {
                FactoryMensagem.mensagemAlerta(MENSAGEM_DE_TELA_ABERTA);
            } else {
                TelaDeHistoricoNota tela = new TelaDeHistoricoNota();
                this.desktopPanel.add(tela);
                Configuracao.setPosicaoInternalFrame(desktopPanel, tela);
                tela.setVisible(true);
            }
        });

        this.btnItemMenuSair.addActionListener(ev -> {
            System.exit(0);
        });
    }
}
