#db_host_oracle: 172.17.0.2
db_host_oracle: localhost
db_user_oracle: api_backup_nota
db_pass_oracle: nota

host: ${db_host_oracle}
user: ${db_user_oracle}
pass: ${db_pass_oracle}


server:
  port: 8081
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:oracle:thin:@${host}:1521:xe
    username: ${user}
    password: ${pass}
    driver-class-name: oracle.jdbc.OracleDriver