
module AccessControlDesktop {
    requires jersey.client;
    requires jakarta.ws.rs;
    requires jersey.common;
    requires jakarta.annotation;
    requires osgi.resource.locator;
    requires jakarta.inject;
    requires jcalendar;
    requires org.hibernate.orm.core;
    requires org.jboss.logging;
    requires java.persistence;
    requires net.bytebuddy;
    requires antlr;
    requires java.transaction;
    requires org.jboss.jandex;
    requires com.fasterxml.classmate;
    requires java.activation;
    requires org.hibernate.commons.annotations;
    requires java.xml.bind;
    requires com.sun.xml.bind;
    requires com.sun.xml.txw2;
    requires com.sun.istack.runtime;
    requires org.jvnet.staxex;
    requires com.sun.xml.fastinfoset;
    requires com.google.gson;
    requires mysql.connector.java;
    requires com.google.protobuf;
    requires org.eclipse.persistence.core;
    requires org.eclipse.persistence.asm;
    requires eclipselink.antlr;
    requires org.eclipse.persistence.jpa;
    requires org.eclipse.persistence.jpa.jpql;
    requires org.eclipse.persistence.moxy;
    requires org.eclipse.persistence.jpa.modelgen.processor;
    requires java.desktop;
    requires java.logging;
    requires java.base;
}
